export const odds = [
  {
    id: "livars01",
    home: "liv",
    away: "ars",
    winner: 737,
    win: 2.26,
    draw: 3.05,
    lose: 3.6,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livbha02",
    home: "liv",
    away: "bha",
    winner: 162,
    win: 1.57,
    draw: 3.96,
    lose: 6.27,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livbur02",
    home: "liv",
    away: "bur",
    winner: 342,
    win: 1.85,
    draw: 3.48,
    lose: 4.51,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livmnc03",
    home: "liv",
    away: "mnc",
    winner: 520,
    win: 2.06,
    draw: 3.22,
    lose: 3.96,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livlee04",
    home: "liv",
    away: "lee",
    winner: 162,
    win: 1.57,
    draw: 3.96,
    lose: 6.27,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livsun05",
    home: "liv",
    away: "sun",
    winner: 162,
    win: 1.57,
    draw: 3.96,
    lose: 6.27,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livbre06",
    home: "liv",
    away: "bre",
    winner: 737,
    win: 2.26,
    draw: 3.05,
    lose: 3.6,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livbou06",
    home: "liv",
    away: "bou",
    winner: 94.3,
    win: 1.37,
    draw: 4.88,
    lose: 8.63,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livmnu07",
    home: "liv",
    away: "mnu",
    winner: 342,
    win: 1.85,
    draw: 3.48,
    lose: 4.51,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livche08",
    home: "liv",
    away: "che",
    winner: 1442,
    win: 2.87,
    draw: 3.56,
    lose: 2.38,
    code: "DHA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livtot08",
    home: "liv",
    away: "tot",
    winner: 94.3,
    win: 1.37,
    draw: 4.88,
    lose: 8.63,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "mncliv09",
    home: "mnc",
    away: "liv",
    winner: 1655,
    win: 2.58,
    draw: 3.2,
    lose: 2.87,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "cheliv09",
    home: "che",
    away: "liv",
    winner: 3235,
    win: 2.13,
    draw: 3.19,
    lose: 3.76,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "notliv09",
    home: "not",
    away: "liv",
    winner: 688,
    win: 3.72,
    draw: 3.08,
    lose: 2.2,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "sunliv09",
    home: "sun",
    away: "liv",
    winner: 473,
    win: 3.94,
    draw: 3.24,
    lose: 2.05,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livnot10",
    home: "liv",
    away: "not",
    winner: 280,
    win: 1.78,
    draw: 3.33,
    lose: 5.33,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livast10",
    home: "liv",
    away: "ast",
    winner: 1038,
    win: 2.43,
    draw: 3.25,
    lose: 3.03,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "astliv11",
    home: "ast",
    away: "liv",
    winner: 1818,
    win: 2.43,
    draw: 3.25,
    lose: 3.03,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "bouliv11",
    home: "bou",
    away: "liv",
    winner: 324,
    win: 4.89,
    draw: 3.35,
    lose: 1.83,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "wolliv11",
    home: "wol",
    away: "liv",
    winner: 1655,
    win: 2.58,
    draw: 3.2,
    lose: 2.87,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "bhaliv11",
    home: "bha",
    away: "liv",
    winner: 473,
    win: 3.94,
    draw: 3.24,
    lose: 2.05,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "leeliv11",
    home: "lee",
    away: "liv",
    winner: 473,
    win: 3.94,
    draw: 3.24,
    lose: 2.05,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "arsliv12",
    home: "ars",
    away: "liv",
    winner: 1568,
    win: 2.59,
    draw: 3.17,
    lose: 2.88,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livnew13",
    home: "liv",
    away: "new",
    winner: 737,
    win: 2.26,
    draw: 3.05,
    lose: 3.6,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livful13",
    home: "liv",
    away: "ful",
    winner: 280,
    win: 1.78,
    draw: 3.33,
    lose: 5.33,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "fulliv14",
    home: "ful",
    away: "liv",
    winner: 688,
    win: 3.72,
    draw: 3.08,
    lose: 2.2,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "burliv15",
    home: "bur",
    away: "liv",
    winner: 1041,
    win: 3.1,
    draw: 3.23,
    lose: 2.4,
    code: "DHA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "mnuliv16",
    home: "mnu",
    away: "liv",
    winner: 1041,
    win: 3.1,
    draw: 3.23,
    lose: 2.4,
    code: "DHA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "newliv17",
    home: "new",
    away: "liv",
    winner: 1568,
    win: 2.59,
    draw: 3.17,
    lose: 2.88,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "eveliv17",
    home: "eve",
    away: "liv",
    winner: 473,
    win: 3.94,
    draw: 3.24,
    lose: 2.05,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "cryliv17",
    home: "cry",
    away: "liv",
    winner: 473,
    win: 3.94,
    draw: 3.24,
    lose: 2.05,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livcry18",
    home: "liv",
    away: "cry",
    winner: 162,
    win: 1.57,
    draw: 3.96,
    lose: 6.27,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "liveve18",
    home: "liv",
    away: "eve",
    winner: 162,
    win: 1.57,
    draw: 3.96,
    lose: 6.27,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livwol18",
    home: "liv",
    away: "wol",
    winner: 520,
    win: 2.06,
    draw: 3.22,
    lose: 3.96,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "livwhu18",
    home: "liv",
    away: "whu",
    winner: 280,
    win: 1.78,
    draw: 3.33,
    lose: 5.33,
    code: "ADH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "whuliv19",
    home: "whu",
    away: "liv",
    winner: 688,
    win: 3.72,
    draw: 3.08,
    lose: 2.2,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "totliv19",
    home: "tot",
    away: "liv",
    winner: 324,
    win: 4.89,
    draw: 3.35,
    lose: 1.83,
    code: "HDA",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  {
    id: "breliv19",
    home: "bre",
    away: "liv",
    winner: 1568,
    win: 2.59,
    draw: 3.17,
    lose: 2.88,
    code: "DAH",
    homeAmount: 0,
    drawAmount: 0,
    awayAmount: 0,
  },
  
];
